package milk.dao;

import milk.models.Point;
import milk.models.User;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

@Component
public class PointsDAO {
    private static Connection conn;
    static String url = null;
    static String username = null;
    static String password = null;
    static {
        InputStream fis;
        Properties property = new Properties();

        try {
            ClassLoader classloader = Thread.currentThread().getContextClassLoader();
            fis = classloader.getResourceAsStream("persistence.properties");

            property.load(fis);

            url = property.getProperty("url");
            username = property.getProperty("username");
            password = property.getProperty("password");
        } catch (IOException e) {
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(url, username, password);
            //conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "123");
        } catch (Exception e1) {
            int a = 0;
        }
    }

    public List<Point> getAll(String userID) throws SQLException{
        List<Point> list = new ArrayList<Point>();
        PreparedStatement ps = conn.prepareStatement("SELECT * FROM points WHERE userID = ?");
        ps.setString(1, userID);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            Point point = new Point(rs.getString(1), rs.getString(2), Double.parseDouble(rs.getString(3)), Double.parseDouble(rs.getString(4)), Integer.parseInt(rs.getString(5)));
            list.add(point);

        }

        return list;
    }

    public void add(Point point) throws SQLException {
        PreparedStatement ps = conn.prepareStatement("INSERT INTO points VALUES (0,?,?,?,?)", Statement.RETURN_GENERATED_KEYS);
        ps.setString(1, point.getUserID().toString());
        ps.setString(2, Double.toString(point.getLat()));
        ps.setString(3, Double.toString(point.getLon()));
        ps.setString(4, Double.toString(point.getCount()));
        ps.execute();
        ResultSet tableKeys = ps.getGeneratedKeys();
        tableKeys.next();
        int autoGeneratedID = tableKeys.getInt(1);
        point.setId(Integer.toString(autoGeneratedID));


    }

}
