package milk.dao;

import milk.models.User;
import org.springframework.stereotype.Component;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

@Component
public class UserDAO {
    private static Connection conn;
    static String url = null;
    static String username = null;
    static String password = null;
    static {
        InputStream fis;
        Properties property = new Properties();

        try {
            ClassLoader classloader = Thread.currentThread().getContextClassLoader();
            fis = classloader.getResourceAsStream("persistence.properties");

            property.load(fis);

            url = property.getProperty("url");
            username = property.getProperty("username");
            password = property.getProperty("password");
        } catch (IOException e) {
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(url, username, password);
            //conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "123");
        } catch (Exception e1) {
            int a = 0;
        }
    }

    public List<User> getAll() throws SQLException{
        List<User> list = new ArrayList<User>();
        PreparedStatement ps = conn.prepareStatement("SELECT * FROM users");
        ResultSet rs = ps.executeQuery();
          while (rs.next()) {
            User user = new User(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4));
            list.add(user);

        }

        return list;
    }

    public User getOne(String email) {
        try {
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM users where email = ?");
            ps.setString(1, email);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                User user = new User(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4));
                return user;
            }
        }
        catch (SQLException e) {

        }

        return null;
    }

    public User getOneLogin(String email, String password) {
        try {
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM users where email = ? AND password = ?");
            ps.setString(1, email);
            ps.setString(2, password);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                User user = new User(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4));
                return user;
            }
        }
        catch (SQLException e) {

        }

        return null;
    }

    public void add(User user) throws SQLException {
        PreparedStatement ps = conn.prepareStatement("INSERT INTO users VALUES (0,?,?,?)", Statement.RETURN_GENERATED_KEYS);
        ps.setString(1, user.getName());
        ps.setString(2, user.getEmail());
        ps.setString(3, user.getPassword());
        ps.execute();
        ResultSet tableKeys = ps.getGeneratedKeys();
        tableKeys.next();
        int autoGeneratedID = tableKeys.getInt(1);
        user.setId(Integer.toString(autoGeneratedID));


    }
}
